version: '3'

volumes:
  data:

services:
  mysql:
    image: mysql:8.0.29
    env_file:
      - "./config/env.common"
      - "./config/env.${IDC_NAME}"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--lower_case_table_names=0"
      ]
